apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  labels:
    app: school
    env: {{ .Values.env }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
    prometheus.io/path: '/metrics' 
spec:
  ports:
  - port: 80
    protocol: TCP
    name: school
  selector:
    app: school
  type: NodePort